"token"="MTEzNDU5MjMyOTAxNDA1MDgzNg.GsYVE2.bvPsRSkEirvKFQhsfA-puWtNDU-clMmm0zyf90" # the bot's token
"prefix"="!" # prefix used to denote commands

[music]
# Options for the music commands
"max_volume"=250 # Max audio volume. Set to -1 for unlimited.
